fix(publikator): save comment id and marker at once
republik/plattform pull request #131
Opened 2022-06-12 07:49 UTC by patrickvenetz

If you pick a marker and then submit an initial comment, picked marker got lost.

https://user-images.githubusercontent.com/331800/173222928-324c5e20-f931-4a16-9432-4f0ad9f8f714.mov

This Pull Request fixes that by storing changes in component state (`parentId`, `marker`) and upon closing overlay, calls `editor.change`.

https://user-images.githubusercontent.com/331800/173222825-ff5dbc47-9688-49a3-81f9-52a52a78c6d4.mov

2022-06-14 09:10 UTC, annatraussnig commented on apps/publikator/components/editor/modules/memo/index.js
> -        data: node.data.set(key, value),
```
const persistData = (key, value) =>
    editor.change((change) => {
      change.setNodeByKey(node.key, {
        data: node.data.merge({ [key]: value }),
      })
    })
```

2022-06-14 09:11 UTC, annatraussnig requested changes
Thanks for taking this on ❤️ 
I believe just applying `data.merge` instead of `data.set` is enough to solve the problem. No need for states or any of the other changes.

2022-06-14 09:12 UTC, annatraussnig commented on apps/publikator/components/editor/modules/memo/index.js
> -        data: node.data.set(key, value),
I believe this is the only change you need for the bug to go away.

2022-06-14 17:49 UTC, patrickvenetz commented
Did give it a spin and it did not work.

Maybe this is a look-me-over-the-shoulder-thing.

2022-09-20 12:10 UTC, annatraussnig approved these changes
All our reviewers are currently busy, please hold the line.
All our reviewers are currently busy, please hold the line.
All our reviewers are currently busy, please hold the line.

2022-09-20 13:20 UTC, merged