feat: add read-aloud publish notifications
republik/plattform pull request #308
Opened 2022-12-09 12:52 UTC by trm217

- feat(api): extend publish mutation to accept notifyReadAloudSubscribers param
- feat(api): extend EventObjectType enum with the value 'ReadAloud'
- feat(publikator): add checkbox to publikator that allows sending notifcation for read-aloud
- fix(documents): fallback to doc.repoId

2023-01-18 15:11 UTC, annatraussnig approved these changes
Looks good – a few notes.

Backend code not reviewed as thoroughly as publikator/www, since I'm less familiar with the codebase.

2023-01-18 15:55 UTC, annatraussnig commented on apps/publikator/components/Publication/PublicationForm.js
> +  mutation publish($repoId: ID!, $commitId: ID!, $input: PublishInput!) {
actually the backend calls it settings -> i changed it in the code

2023-01-18 15:56 UTC, annatraussnig commented on apps/www/components/ActionBar/index.js
> +              !(subscription?.object?.id === document.id && !!meta.format),
somehow I needed the conditionals `subscription?.object?.id` for it to work locally

2023-01-18 16:32 UTC, annatraussnig requested changes

2023-01-18 16:32 UTC, annatraussnig commented on apps/www/components/ActionBar/AudioInfo.js
> +    ({ object: { id } }) => id === documentId,
Found out while testing that for articles which aren't a format and don't have a republik author profile, there are no nodes returned here.
E.g.:
https://www.republik.ch/2023/01/17/kunstkolumne-vahland-die-kunst-der-einigung
([graphql query](https://api.republik.ch/graphiql/?query=%7B%0A%20%20document(path%3A%20%22%2F2023%2F01%2F17%2Fkunstkolumne-vahland-die-kunst-der-einigung%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20subscriptions%3A%20subscribedBy(onlyMe%3A%20true)%20%7B%0A%20%20%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20isEligibleForNotifications%0A%20%20%20%20%20%20%20%20filters%0A%20%20%20%20%20%20%20%20active%0A%20%20%20%20%20%20%20%20object%20%7B%0A%20%20%20%20%20%20%20%20%20%20...%20on%20Document%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A))

This means the subscribe button never comes up in such articles, for which the condition is:
`(!!data || !loading) && readAloudSubscription`

Probably this isn't wanted

2023-03-03 16:43 UTC, trm217 commented on apps/www/components/ActionBar/Audio/Info.js
> +  if (!readAloudSubscription?.isEligibleForNotifications) {
@patrickvenetz This here is false for me when developing against staging.
If this is false, the callout renders without content. Perhaps if this is false, we should not render the option to subscribe at all and instead fallback to play synthetic if that is available.

2023-03-10 12:19 UTC, merged