Synthetic Read Aloud
republik/plattform pull request #46
Opened 2022-02-23 20:35 UTC by patrickvenetz

2022-02-24 10:32 UTC, ovbm commented
frontend implementation:
A section below the action bar. Only visible if audioSource.kind === syntheticReadAloud
The play button is omitted in the Feed so as to not confuse users who expect non-synthetic audio from the current play buttons:
<img width="577" alt="Screenshot 2022-02-24 at 11 15 29" src="https://user-images.githubusercontent.com/20746301/155507463-3b838980-761d-47f4-a5de-83ed8004fcbd.png">
<img width="588" alt="Screenshot 2022-02-24 at 11 27 49" src="https://user-images.githubusercontent.com/20746301/155507489-13c579e4-5cea-4e28-848a-a4edae26f8a6.png">
<img width="331" alt="Screenshot 2022-02-24 at 11 15 22" src="https://user-images.githubusercontent.com/20746301/155507494-b71c0cdc-fa4c-4952-8298-f943a59003b2.png">

2022-02-24 11:18 UTC, ovbm commented
<img width="783" alt="Screenshot 2022-02-24 at 12 13 23" src="https://user-images.githubusercontent.com/20746301/155514521-faf5a980-dc9f-4613-8551-e3ea777e0f72.png">
Publikator Buttons

2022-03-18 12:20 UTC, ovbm requested changes

2022-03-18 12:20 UTC, ovbm commented on apps/www/components/Article/SyntheticAudio.tsx
> +const HeadPhonesIcon = () => (
not using this anymore, will delete

2022-03-18 12:20 UTC, ovbm commented on apps/www/components/Article/SyntheticAudio.tsx
> +            Beitrag von synthetischen Stimme vorlesen lassen{' '}
Copy in translation string

2022-03-18 12:30 UTC, ovbm commented
frontend self-review done and some changes made. What's the plan for the full review?

2022-03-21 09:03 UTC, patrickvenetz commented
@fuenkchen will help with API. Not sure how to manage Publikator and Frontend.

2022-03-22 10:56 UTC, fuenkchen reviewed
API part is looking good to me. Just a few comments/hints, maybe they are getting obsolete anyways with fine tuning while testing internally.

2022-03-22 10:56 UTC, fuenkchen commented on packages/backend-modules/translate/translations.json
> +      "value": "Commit darf nicht als Derivat generiert werden"
This message will be exposed to end users in Publikator, correct? It's a bit cryptic imho. (Same with value below)

2022-03-22 14:20 UTC, patrickvenetz commented on packages/backend-modules/types/index.d.ts
> +  scope?: 'request' | 'socket' | 'middleware' | 'master'
Going for `scheduler`.

2022-03-22 16:19 UTC, fuenkchen approved these changes
API part approved

2022-03-22 17:05 UTC, annatraussnig reviewed
The Publikator part looks good at first glance but I haven't got much understanding of the project. It's very standard React code, so I trust @ovbm's review, who knows the project requirements much better than I do.

2022-03-23 06:34 UTC, ovbm approved these changes

2022-03-23 08:18 UTC, merged