fix(auth): check if user is deleted when resolving token
republik/plattform pull request #510
Opened 2023-07-04 09:53 UTC by lucianak

When an access token of any type is resolved, it checks if the user has been deleted (for the cases where the user record has to be kept after deletion for administrative reasons).

2023-07-04 10:14 UTC, lucianak commented
Before change: the GraphQl query 
```
{
  user(slug:"0dc984eb-b07e-438d-b4b0-fa8679c7894d") {
    customPackages {
      name
      suggestedTotal
    }
  }
}
```
with a deleted user gives
```
{
  "data": {
    "user": {
      "customPackages": [
        {
          "name": "PROLONG",
          "suggestedTotal": null
        }
      ]
    }
  }
}
```

After change: the same GraphQl query with the deleted user gives
```
{
  "data": {
    "user": null
  },
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2023-07-04T10:12:01.368Z",
      "endTime": "2023-07-04T10:12:01.677Z",
      "duration": 308520362,
      "execution": {
        "resolvers": [
          {
            "path": [
              "user"
            ],
            "parentType": "queries",
            "fieldName": "user",
            "returnType": "User",
            "startOffset": 775412,
            "duration": 307629822
          }
        ]
      }
    }
  }
}
```

2023-07-04 10:18 UTC, patrickvenetz commented on packages/backend-modules/auth/lib/AccessToken.js
> +    if (userRecord.revokedAt) {
`revokedAt` does not exist in user rows.

(This will always default to `true`.)

2023-07-04 10:23 UTC, patrickvenetz requested changes

2023-07-04 10:23 UTC, patrickvenetz commented on packages/backend-modules/auth/lib/AccessToken.js
> +    if (userRecord.deletedAt) {
This will throw an error if `findOne` returns `null`.

```
TypeError: Cannot read properties of null (reading 'deletedAt')
```

2023-07-04 10:25 UTC, patrickvenetz commented on packages/backend-modules/auth/lib/AccessToken.js
> +    if (userRecord.deletedAt) {
Albeit code might work eventually, maybe revert to previous code and extend query like so:

```
   const key = await pgdb.public.users.findOneFieldOnly(
      { id: userId, 'deletedAt !=': null },
      'accessKey',
    )
```

2023-07-04 16:40 UTC, lucianak commented
For testing: 

- create token:
```
{
  user(slug: "userId") {
    accessToken(scope: CUSTOM_PLEDGE)
  }
}
```

- check if token resolves to user or to `null`:
```
{
  user(accessToken: "tokenGoesHere") {
    customPackages {
      name
      suggestedTotal
    }
  }
}
```

2023-07-05 07:10 UTC, patrickvenetz approved these changes
LGTM

2023-07-06 09:51 UTC, merged