feat: onboarding audience
republik/plattform pull request #513
Opened 2023-07-06 16:31 UTC by lucianak

New members should be added to the onboarding audience when they get a membership for the first time, and removed after they complete the onboarding journey

2023-07-19 11:51 UTC, annatraussnig reviewed
Looks pretty good :) 
Added a few JS suggestions left and right… Looking forward to seeing it in action!

2023-07-19 11:51 UTC, annatraussnig commented on packages/backend-modules/mail/MailchimpInterface.js
>      buildMembersApiUrl(email) {
```suggestion
    buildMembersApiUrl(email, audienceId = MAILCHIMP_MAIN_LIST_ID) {
```
if audienceId is undefined the function would use the given default, i.e. MAILCHIMP_MAIN_LIST_ID

2023-07-19 11:51 UTC, annatraussnig commented on packages/backend-modules/mail/MailchimpInterface.js
>      buildMembersApiUrl(email) {
then you could use `buildMembersApiUrl` everywhere and delete `buildAudienceApiUrl`

2023-07-19 11:51 UTC, annatraussnig commented on packages/backend-modules/mail/MailchimpInterface.js
> +    async updateMemberInAudience(email, data, audienceId) {
maybe here we could reuse `async updateMember(email, data)` but with a default audienceId as well, i.e. `async updateMember(email, data, audienceId = MAILCHIMP_MAIN_LIST_ID)` (if the rest of the logic is exactly the same)

2023-07-19 11:51 UTC, annatraussnig commented on packages/backend-modules/mail/MailchimpInterface.js
> +    buildApiUrl(audienceId, path) {
```suggestion
    buildApiUrl(path, audienceId = MAILCHIMP_MAIN_LIST_ID) {
```
then it's safer if the function is used somewhere random we don't know about…

2023-07-19 11:51 UTC, annatraussnig commented on packages/backend-modules/mail/MailchimpInterface.js
> +    async archiveMemberInAudience(email, audienceId) {
```suggestion
    async archiveMember(email, audienceId = MAILCHIMP_MAIN_LIST_ID) {
```

2023-07-19 11:56 UTC, lucianak commented on packages/backend-modules/republik-crowdfundings/lib/Mail.js
> +const mail = createMail(
audience configuration isn't really used anywhere

2023-07-19 11:57 UTC, lucianak commented on packages/backend-modules/republik-crowdfundings/lib/Mail.js
> +
```suggestion
mail.addUserToAudience = addUserToAudience
```

2023-07-19 11:57 UTC, lucianak commented on packages/backend-modules/republik-crowdfundings/lib/Mail.js
> +    status: MailchimpInterface.MemberStatus.Subscribed,
always gives back status `Subscribed` regardless of actual result

2023-07-19 12:42 UTC, lucianak commented on packages/backend-modules/mail/MailchimpInterface.js
@annatraussnig what do you think?

2023-07-27 16:00 UTC, fuenkchen requested changes
Not finished yet, but I thought, I send these comments already now.

2023-08-03 08:35 UTC, lucianak commented on packages/backend-modules/republik-crowdfundings/lib/Mail.js
> +  MAILCHIMP_MAIN_LIST_ID,
I think AUDIENCE is more explicit, but I didn't want to change too many things of the existing code just yet

2023-08-03 10:09 UTC, fuenkchen commented on packages/backend-modules/republik-crowdfundings/lib/activateMembership.js
> +  return { updatedMembership, hasActiveMembership }
This one was resolved, but changing the return value here has an impact on the mutation `activateMembership` and on mutation `claimMembership` as far as I can see.

2023-08-03 13:53 UTC, fuenkchen approved these changes
lgtm

2023-08-03 14:20 UTC, merged