feat: enricht sentry by setting the user on the error
republik/plattform pull request #568
Opened 2023-09-05 13:25 UTC by trm217

### Descriptions

This PR contains the following changes for the admin & publikator apps:
- Ensure the user is being set on the sentry util.
- add custom 404 pages to both apps to allow for easier navigation on 404.

### Commits
- feat(admin): set active-user as sentry user
- feat(publikator): set active-user as sentry user
- feat(admin): add custom 404 page
- feat(publikator): add custom 404 page
- fix(publikator): rename ME_QUERY constant

2023-09-05 15:53 UTC, jstcki requested changes

2023-09-05 15:53 UTC, jstcki commented on apps/admin/lib/useMe.js
> +  }, [data?.me])
I don't like this as a side effect of useMe. This way, it also doesn't seem to work when the `withMe` HOC is used. So, preferably, the Sentry user should be set explicitly in _app.tsx.

Same concern applies to publikator app.

2023-09-05 15:53 UTC, jstcki commented on apps/admin/components/App.js
> +  useMe()
Noted below, it's really not clear why this is used here (I know it's for the side effect of setting the Sentry user but this should be done explicitly)

2023-09-05 15:53 UTC, jstcki commented on apps/admin/lib/useMe.js
> +  }, [data?.me])
Also, I don't think useEffect should be used? It won't work on the server …

2023-09-06 09:23 UTC, jstcki approved these changes

2023-09-06 09:33 UTC, trm217 commented
Will deploy it later once we're done testing the climate-lab tear-down

2023-09-07 07:28 UTC, merged